name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Supported-Versions-Matrix:
    name: Supported Versions Matrix
    runs-on: ubuntu-latest
    outputs:
      extensions: ${{ steps.supported-versions-matrix.outputs.extensions }}
      version: ${{ steps.supported-versions-matrix.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: supported-versions-matrix
        uses: WyriHaximus/github-action-composer-php-versions-in-range@v1
  Install-Test:
    name: Install test on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    needs:
      - supported-versions-matrix
    strategy:
      matrix:
        php: ${{ fromJson(needs.supported-versions-matrix.outputs.version) }}
    steps:
      - name: Git chechout
        uses: actions/checkout@v3
      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: ${{ join(fromJson(needs.supported-versions-matrix.outputs.extensions), ',') }}
          ini-file: development
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Install dependencies
        uses: ramsey/composer-install@v2
